name: compressed-size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./packages/client

    steps:
      # Use this GitHub Actions at least once in this workflow as soon as possible.
      - uses: technote-space/auto-cancel-redundant-workflow@v1.7.5
      
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3.0.1'
        with:
          lfs: true

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: sudo npm i -g pnpm

      - name: Install Dependencies
        run: pnpm recursive install --frozen-lockfile=false
        
      - uses: preactjs/compressed-size-action@2.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: |
            ./packages/client/dist/**/*.{js,css,woff,woff2}"
            ./packages/server/dist/**/*.{js,css,woff,woff2}"
          # Always ignore SourceMaps and node_modules
          exclude: "{**/*.map,**/node_modules/**}"
          strip-hash: "\\.(\\w{8})\\."
