name: developer-build

on:
  push:
    branches:
      - develop

jobs:
  gh_developer_build:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./packages/client

    steps:
      # Use this GitHub Actions at least once in this workflow as soon as possible.
      - uses: technote-space/auto-cancel-redundant-workflow@v1.7.5

      - name: 'Checkout source code'
        uses: 'actions/checkout@v2.3.5'
        with:
          lfs: true

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: sudo npm i -g pnpm

      - name: Install Dependencies
        run: pnpm recursive install --frozen-lockfile=false

      - run: pnpm run build

      - name: Archive Client Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'diode-client-${{ github.sha }}.zip'
          path: 'packages/client/dist'

      - name: Archive Server Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'diode-server-${{ github.sha }}.zip'
          path: 'packages/server/src'

      - name: Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: true
          automatic_release_tag: 'latest'
          title: 'Development Build (${{ github.sha }})'
          files: |
            diode-client-${{ github.sha }}.zip
            diode-server-${{ github.sha }}.zip
