name: linting

on: push

jobs:
  gh_linting:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./packages/client

    steps:
      # Use this GitHub Actions at least once in this workflow as soon as possible.
      - uses: technote-space/auto-cancel-redundant-workflow@v1

      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          lfs: true

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: sudo npm i -g pnpm

      - name: Install Dependencies
        run: pnpm recursive install --frozen-lockfile=false

      - run: pnpm run lint
