name: tagged-release

on:
  push:
    tags:
      - 'v*'

jobs:
  gh_tagged_release:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./packages/client

    steps:
      # Use this GitHub Actions at least once in this workflow as soon as possible.
      - uses: technote-space/auto-cancel-redundant-workflow@v1.7.5

      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          lfs: true

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: sudo npm i -g pnpm

      - name: Install Dependencies
        run: pnpm recursive install --frozen-lockfile=false

      - run: pnpm run build

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Archive Client Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'diode-client-${{ steps.get_version.outputs.VERSION }}.zip'
          path: 'packages/client/dist'

      - name: Archive Server Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'diode-server-${{ steps.get_version.outputs.VERSION }}.zip'
          path: 'packages/server/src'

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: 'false'
          PRE_RELEASE: 'false'
          CHANGELOG_FILE: 'CHANGELOG.md'
          ALLOW_EMPTY_CHANGELOG: 'false'
          ALLOW_TAG_PREFIX: 'true'
        with:
          args: |
            diode-client-${{ steps.get_version.outputs.VERSION }}.zip
            diode-server-${{ steps.get_version.outputs.VERSION }}.zip
